// we will be updating the database as the user is typing in the text editor but we don't want
// to do that every single time a key is hit so this function allow the database be updated 
// only after there has been a delay between keystrokes.
export default function debounce(a, b, c){
    let d, e;
    return function(){
        function h(){
            d=null;
            c||(e=a.apply(f,g));
        }
        let f=this, g=arguments;
        return(clearTimeout(d),d=setTimeout(h,b), c&&!d&&(e=a.apply(f,g)),e)
    }
};



// this remove html tags from previews generated by react quill or so
export function removeHTMLTags(str){
    return str.replace(/<[^>]*>?/gm, "");
};


